config/routes.rb
BookStore::Application.routes.draw do

  get "notices/admin"
  resources :notices

  get "docs/admin"

  resources :docs

  get "events/admin"
  resources :events

  resources :brands

  resources :e_readings

  get "book_flow/new"

  get "book_flow/create"

  get "book_flow/edit"

  get "book_flow/update"

  get "book_flow/destroy"

  get "book_flow/show"

  get "book_flow/index"

  get "sessions/new"

  resources :sessions,:only=>[:new,:create,:destroy]

  match '/signup',:to=>'users#new'
  match '/signin',:to => 'sessions#new'
  match '/signout',:to=> 'sessions#destroy'
  match '/search',:to=>'products#search'
  match '/admin', :to => 'page#admin'

  resources :book_flows do

  end

  resources :users

  resources :best_sellers

  get "news/admin"
  resources :news

  resources :publishers

  resources :authors

  resources :categories

  get "products/book_list"

  resources :products

  get "books/index"

  get "books/show"

  get "books/destroy"

  get "books/create"

  get "books/new"

  get "book/index"

  get "book/new"

  get "book/destroy"

  root :to=> "page#home"

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  attr_accessible :title, :content

  def self.get_notices(count)
    Notice.order("created_at DESC").all[0...count]
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all

    render :layout => "admin"
  end

  def admin
    @notices = Notice.all

    render :layout => "admin"
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    @notice = Notice.find(params[:id])

    @best_sellers = BestSeller.get(7)
    @notices = Notice.get_notices(6)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/new
  # GET /notices/new.json
  def new
    @notice = Notice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notice }
    end
  end

  # GET /notices/1/edit
  def edit
    @notice = Notice.find(params[:id])
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(params[:notice])

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render json: @notice, status: :created, location: @notice }
      else
        format.html { render action: "new" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notices/1
  # PUT /notices/1.json
  def update
    @notice = Notice.find(params[:id])

    respond_to do |format|
      if @notice.update_attributes(params[:notice])
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice = Notice.find(params[:id])
    @notice.destroy

    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :ok }
    end
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/admin.html.erb
<h1>最新公告</h1>

<table class="table">
  <tr>
    <th>标题</th>
    <th>正文</th>
    <th></th>
    <th></th>
  </tr>

<% @notices.each do |notice| %>
  <tr>
    <td><%= notice.title %></td>
    <td><%= notice.content %></td>
    <td><%= link_to '查看', notice, :class => "btn" %></td>
    <td><%= link_to '编辑', edit_notice_path(notice), :class => "btn" %></td>
    <td><%= link_to '删除', notice, :class => "btn", :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '添加 最新公告', new_notice_path %>

app/views/notices/edit.html.erb
<h1>Editing notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<h1>Listing notices</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notices.each do |notice| %>
  <tr>
    <td><%= notice.title %></td>
    <td><%= notice.content %></td>
    <td><%= link_to 'Show', notice %></td>
    <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
    <td><%= link_to 'Destroy', notice, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New notice</h1>

<%= render 'form' %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content" style="position: relative;top:-15px;">

  <div class="content_sales">
    <div class="sales_left">
      <div class="content_float_left_top" style="height: 15px;">
      </div>

      <div class="content_book_detail">
        <div class="title">
          <%= @notice.title%>
        </div>

        <hr style="width: 600px;margin-left: 0px;" >
        <div class="bottom">
          <p ><%= simple_format @notice.content%></p>
        </div>
      </div>
    </div>

    <%= render :partial => 'products/sales_right'%>
  </div>

  <%= render :partial => 'page/content_bottom' %>
  <div class="clear"></div>

</div>