config/routes.rb
BookStore::Application.routes.draw do

  get "notices/admin"
  resources :notices

  get "docs/admin"

  resources :docs

  get "events/admin"
  resources :events

  resources :brands

  resources :e_readings

  get "book_flow/new"

  get "book_flow/create"

  get "book_flow/edit"

  get "book_flow/update"

  get "book_flow/destroy"

  get "book_flow/show"

  get "book_flow/index"

  get "sessions/new"

  resources :sessions,:only=>[:new,:create,:destroy]

  match '/signup',:to=>'users#new'
  match '/signin',:to => 'sessions#new'
  match '/signout',:to=> 'sessions#destroy'
  match '/search',:to=>'products#search'
  match '/admin', :to => 'page#admin'

  resources :book_flows do

  end

  resources :users

  resources :best_sellers

  get "news/admin"
  resources :news

  resources :publishers

  resources :authors

  resources :categories

  get "products/book_list"

  resources :products

  get "books/index"

  get "books/show"

  get "books/destroy"

  get "books/create"

  get "books/new"

  get "book/index"

  get "book/new"

  get "book/destroy"

  root :to=> "page#home"

end

app/views/page/_author_flow.html.erb
<div id="demo" style="overflow: hidden; width: 690px; height: 92px"> 
  <table align="center" border="0" cellpadding="0" cellspacing="0"> 
    <tbody><tr> 
        <td id="demo1"> 
          <table id="ctl00_CenterContent_DListAuthor" cellspacing="0" border="0" style="height:92px;width:1500px;border-collapse:collapse;"> 
            <tbody><tr> 
                <td align="center" style="width:100px;"> 

                  <% Author.for_author_flow(10).each do |author|%>
                    <a id="ctl00_CenterContent_DListAuthor_ctl00_AuthorShow" title="<%= author.name%>" href="<%= author_path(author)%>" target="_blank">
                      <%= image_tag author.avatar_url, :style=>"width: 92px; height: 92px; border:0px;"%>
                    </a>
                    </td><td align="center" style="width:100px;"> 
                  <% end%>



                  <a id="ctl00_CenterContent_DListAuthor_ctl00_AuthorShow" title="张爱玲" href="http://www.readinglife.com/zhangailing" target="_blank">
                    <%= image_tag "6240000014.jpg", :style=>"width: 92px; height: 92px; border:0px;"%>
                  </a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl01_AuthorShow" title="三毛" href="http://www.readinglife.com/sanmao" target="_blank">
                    <%=image_tag "6240000015.jpg", :style=>"width: 92px; height: 92px; border:0px;"%>
                  </a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl02_AuthorShow" title="张小娴" href="http://www.readinglife.com/zhangxiaoxian" target="_blank">
                    <%= image_tag "6240000016.jpg", :style=>"width: 92px; height: 92px; border:0px;"%>
                  </a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl03_AuthorShow" title="安妮宝贝" href="http://www.readinglife.com/annibaobei" target="_blank">
                    <%= image_tag "6240000017.jpg", :style=>"width: 92px; height: 92px; border:0px;"%>
                  </a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl04_AuthorShow" title="陈忠实" href="http://www.readinglife.com/chenzhongshi" target="_blank">
                    <%=image_tag "6240000022.jpg", :style=>"width: 92px; height: 92px; border:0px;"%>
                  </a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl05_AuthorShow" title="沈从文" href="http://www.readinglife.com/shencongwen" target="_blank">
                    <%= image_tag "6240000036.jpg", :style=>"width: 92px; height: 92px; border:0px;"%>
                  </a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl06_AuthorShow" title="艾丽丝·门罗" href="http://www.readinglife.com/W0005" target="_blank">
                    <%= image_tag "6240000046.jpg", :style=>"width: 92px; height: 92px; border:0px;"%>
                  </a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl07_AuthorShow" title="斯宾塞·约翰逊" href="http://www.readinglife.com/W1035" target="_blank"><img src="./新经典悦读网-新经典文化_files/6240000095.jpg" style="width: 92px; height: 92px; border:0px;"></a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl08_AuthorShow" title="松本清张" href="http://www.readinglife.com/W2021" target="_blank"><img src="./新经典悦读网-新经典文化_files/6240000096.jpg" style="width: 92px; height: 92px; border:0px;"></a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl09_AuthorShow" title="谢尔·希尔弗斯坦" href="http://www.readinglife.com/W1041" target="_blank"><img src="./新经典悦读网-新经典文化_files/6240000105.jpg" style="width: 92px; height: 92px; border:0px;"></a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl10_AuthorShow" title="岩井俊二" href="http://www.readinglife.com/W2025" target="_blank"><img src="./新经典悦读网-新经典文化_files/6240000107.jpg" style="width: 92px; height: 92px; border:0px;"></a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl11_AuthorShow" title="村上春树" href="http://www.readinglife.com/W1002" target="_blank"><img src="./新经典悦读网-新经典文化_files/6240000117.jpg" style="width: 92px; height: 92px; border:0px;"></a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl12_AuthorShow" title="宫部美雪" href="http://www.readinglife.com/W1004" target="_blank"><img src="./新经典悦读网-新经典文化_files/6240000122.jpg" style="width: 92px; height: 92px; border:0px;"></a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl13_AuthorShow" title="范稳" href="http://www.readinglife.com/fanwen" target="_blank"><img src="./新经典悦读网-新经典文化_files/NoImage.gif" style="width: 92px; height: 92px; border:0px;"></a> 
                  </td><td align="center" style="width:100px;"> 





                  <a id="ctl00_CenterContent_DListAuthor_ctl14_AuthorShow" title="路遥" href="http://www.readinglife.com/luyao" target="_blank"><img src="./新经典悦读网-新经典文化_files/6240000033.jpg" style="width: 92px; height: 92px; border:0px;"></a> 
                </td> 
              </tr> 
          </tbody></table> 
        </td> 
        <td id="demo2"> 
        </td> 
      </tr> 
  </tbody></table> 
</div> 
<script language="javascript" type="text/javascript"> 
  <!--
  var demo = document.getElementById("demo");
  var demo1 = document.getElementById("demo1");
  var demo2 = document.getElementById("demo2");
  var speed = 18;    //数值越大滚动速度越慢
  demo2.innerHTML = demo1.innerHTML
  function Marquee(){
    if(demo.scrollLeft >= demo1.offsetWidth)
      demo.scrollLeft-=demo1.offsetWidth
    else{
      demo.scrollLeft++
    }
  }
var MyMar = setInterval(Marquee,speed);
demo.onmouseover = function(){clearInterval(MyMar)}
demo.onmouseout = function(){MyMar = setInterval(Marquee,speed)}
-->
</script> 
<div class="DivBlank"></div> 

app/views/page/_author_table.html.erb
<table border="0" cellspacing="0" cellpadding="0" width="100%"> 
  <tbody> 
    <tr bgcolor="#ffffff" width=""> 
      <td bgcolor="#f1f1f1" valign="top" rowspan="3" width="0" align="middle"> 
        <table border="0" cellspacing="0" cellpadding="0" width="0"> 
          <tbody></tbody></table></td> 
      <td style="TEXT-ALIGN: left" class="font_color_01" bgcolor="#f1f1f1"><strong>&nbsp;华语作家圈：</strong>&nbsp;<a href="http://www.readinglife.com/zhangailing">张爱玲</a> |&nbsp;<a href="http://www.readinglife.com/sanmao">三毛</a> |&nbsp;<a href="http://www.readinglife.com/shencongwen">沈从文</a> |&nbsp;<a href="http://www.readinglife.com/linhaiyin">林海音</a> |&nbsp;<a href="http://www.readinglife.com/chenzhongshi">陈忠实</a> |&nbsp;<a href="http://www.readinglife.com/gaojianqun">高建群</a> |&nbsp;<a href="http://www.readinglife.com/luyao">路遥</a> | <a href="http://www.readinglife.com/liuqingbang">刘庆邦</a> |&nbsp;<a href="http://www.readinglife.com/yanlianke">阎连科</a> | <a href="http://www.readinglife.com/annibaobei">安妮宝贝&nbsp;</a>| <a href="http://www.readinglife.com/zhangxiaoxian">张小娴</a></td></tr> 
    <tr> 
      <td style="TEXT-ALIGN: left" class="font_color_01"><strong>&nbsp;欧美作家圈：</strong> <a href="http://www.readinglife.com/W0001">托妮·莫里森</a> | <a href="http://www.readinglife.com/W0002">多丽丝·莱辛</a> |&nbsp;<a href="http://www.readinglife.com/W1041">希尔弗斯坦</a> |&nbsp;<a href="http://www.readinglife.com/W0004">保罗·柯艾略</a> | <a href="http://www.readinglife.com/W0005">艾丽丝·门罗 </a>| <a href="http://www.readinglife.com/W0003">杜鲁门·卡波特</a> | <a href="http://www.readinglife.com/W1028">帕克丝特</a></td></tr> 
    <tr> 
      <td style="TEXT-ALIGN: left" class="font_color_01" bgcolor="#f1f1f1"><strong>&nbsp;日韩作家圈：</strong> <a href="http://www.readinglife.com/W2026">远藤周作 </a>| <a href="http://www.readinglife.com/W1008">东野圭吾</a> | <a href="http://www.readinglife.com/W2025">岩井俊二</a> | <a href="http://www.readinglife.com/W1004">宫部美雪</a> |&nbsp;<a href="http://www.readinglife.com/W2021">松本清张</a> |&nbsp;<a href="http://www.readinglife.com/W2016">山冈庄八</a> |&nbsp;<a href="http://www.readinglife.com/W2013">柳美里</a> | <a href="http://www.readinglife.com/W1006">黑柳彻子</a> | <a href="http://www.readinglife.com/W1010">金河仁</a></td></tr></tbody></table> 

app/views/page/_classic_pic_list.html.erb
<div id="ctl00_CenterContent_DivJDJB"> 
  <a href="http://www.readinglife.com/News/ListArticle.aspx?QSortId=91"> 
    <div class="Book_Left_Title0"> 
      <h1> 经典简报</h1>
    </div>
  </a> 
</div> 
<div class="DivBlank"> 
</div> 
<div style="width: 235px; overflow: hidden;">
  <% if @classic_products!=nil%>
    <% @classic_products.each do |product|%>
      <% if product.promote_img_name != nil%>
      <div style="CURSOR: pointer">&nbsp;<a href="<%= product_path(product.id)%>"><%=image_tag product.promote_img_name, :border=>"0"%></a></div>
      <% end%>
    <% end%>
  <% end%>

  <div style="CURSOR: pointer">&nbsp;<%=image_tag "20100813155816189.jpg", :border=>"0"%><a href="http://www.readinglife.com/Upload/Special/dscdy_100511/Default.asp"></a></div> 
  <div style="CURSOR: pointer">&nbsp;<%= image_tag "20100813160208749.jpg", :border=>"0"%></div> 
  <div style="CURSOR: pointer">&nbsp;<a href="http://www.readinglife.com/Upload/Special/Zhangxiaoxian_100309/Default.asp"><%=image_tag "20100406173907637.jpg",  :style=>"BORDER-LEFT-COLOR: #eeeeee; FILTER: ; BORDER-BOTTOM-COLOR: #eeeeee; WIDTH: 220px; BORDER-TOP-COLOR: #eeeeee; HEIGHT: 80px; BORDER-RIGHT-COLOR: #eeeeee", :height=>"80", :alt=>"张小娴爱情长篇力作：我终究是爱你的", :hspace=>"0", :width=>"220", :vspace=>"1", :border=>"1"%></a></div> 
  <div style="CURSOR: pointer">&nbsp;<%= image_tag "20100813155915261.jpg", :border=>"0"%><a href="http://www.readinglife.com/Upload/Special/lxzb/Default.asp"></a></div> 
  <div style="CURSOR: pointer">&nbsp;<%= image_tag "20100813155955192.jpg", :border=>"0"%><a href="http://www.readinglife.com/GSpecial/Special-751001020002.html"></a></div> 
  <div style="CURSOR: pointer">&nbsp;<a href="http://www.readinglife.com/Goods/Book-110009120087.html"><%= image_tag "20100301154315925.gif",:style=>"BORDER-LEFT-COLOR: #eeeeee; FILTER: ; BORDER-BOTTOM-COLOR: #eeeeee; WIDTH: 220px; BORDER-TOP-COLOR: #eeeeee; HEIGHT: 80px; BORDER-RIGHT-COLOR: #eeeeee",:height=>"80", :alt=>"张爱玲全集-小团圆", :hspace=>"0", :width=>"220", :vspace=>"1", :border=>"1"%></a></div> 
  <div style="CURSOR: pointer">&nbsp;<%= image_tag "20100813163235717.jpg", :border=>"0"%>&nbsp;</div> 
</div> 

app/views/page/_content.html.erb
<div class="content">
  <%= render :partial => 'content_top' %>

  <%= render :partial => 'content_middle' %>

  <%= render :partial => 'content_bottom' %>

  <div class="clear"></div>
</div>

app/views/page/_content_bottom.html.erb
<div class="content_bottom">
  <div class="content_bottom_left">
    <div class="text_top" style="padding-top: 40px;">
      作者风采
    </div>
  </div>
  <div class="content_bottom_middle"></div>
  <div class="content_bottom_right">

    <ul>
      <% EReading.top(7).each do |eReading| #Author.for_author_flow(5).each do |author|%>
        <li>
          <%= link_to (image_tag eReading.avatar.url), eReading%>
          <p style="margin-top: 5px"></p>
          <p>
            <%= link_to eReading.name,eReading.url%>
          </p>
        </li>
      <% end%>
    </ul>

  </div>
  <div class="clear"></div>
</div>

app/views/page/_content_middle.html.erb
<div class="content_middle">
  <%= render :partial => 'content_middle_left' %>
  <%= render :partial => 'content_middle_right' %>
  <div class="clear"></div>
</div>

app/views/page/_content_middle_right.html.erb
<div class="content_float_right">
  <div  class="content_float_right_top" style="background-image: url('/images/left_top.png');height: 38px;overflow: hidden;">
    <div class="text_top">关注榜</div>
  </div>
  <div class="content_float_right_middle">
    <% i = 0%>
    <% @best_sellers.each do |book|%>
      <% if book!= nil%>
        <% i+=1%>
        <div class="right_cont">
          <div class="left">
            <%=if book!=nil then link_to((image_tag book.image.url(:thumb),:size=>"61x89"),book) end%>
          </div>
          <div class="right">
            <h1>
              <%= "0" + i.to_s if book!= nil%>
            </h1>
            <p>
            <%= if book!=nil then link_to((truncate book.title,:length=>9),book,:class=>:gray) end%>
            </p>
            <span class="writer">
              <%= if book!=nil&&book.author!=nil then "作者：" +  truncate(book.author.name,:length => 9) end%>
            </span>
          </div>
          <div class="clear"></div>
        </div>
        <div class="divi"></div>
      <% end%>
    <% end%>  
  </div>
  <div class="content_float_right_bottom" style="background-image: url('/images/left_bottom.png');height: 7px;position: relative;" ></div>
</div>

<!--
<a href='http://e.weibo.com/hunanrenmin'>
<div class="weibo">
  <img class='wei_icon' src='/images/LOGO_64x64.png'></img>

  <div class='wei_content'>
    <span>新浪微博</span>
    <p>去看看 @湖南人民出版社</p>
  </div>
</div>
</a>
-->

app/views/page/_content_top.html.erb
<div class="content_top">
  <div class="content_float_left">
    <div class="content_float_left_top">
      <a href="/news">
        <div style="float:left;color:#ce691b;font-size: 16px;font-weight:bold;padding-top: 11px;padding-left: 20px">
          活动现场
        </div>
      </a>
      <a href='/events'>
        <div style="color:#ce691b;font-size: 16px;font-weight:bold;padding-top: 11px;padding-right: 272px; text-align:right;">
          出版须知
        </div>
      </a>

    </div>
    <div class="content_float_left_middle">

    </div>
    <div class="content_float_left_bottom">
      <div class="left">
        <h2>
          <%= if @head_news!=nil then link_to((truncate @head_news.title,:length=>16),@head_news,:style => "color:#d17939;text-decoration:none") end%> 
        </h2>
        <p >
          <%= if @head_news!=nil then truncate @head_news.content,:length=>70 end%>
        </p>
        <%= if @head_news!=nil then link_to((image_tag @head_news.image(:medium),:height=>110),@head_news) end%>
      </div>
      <div class="right">
        <ul>
          <% if @news_list != nil%>
            <% @news_list.each do |news|%>
              <li>
                <% if news!=nil then%>
                  <%= link_to((truncate news.title,:length=>22),news,:style=>"text-decoration:none;color:#333")%> <span class="date"><%= news.created_at.strftime("%Y-%m-%d")%></span>
                <% end%>
              </li>
            <% end%>
          <% end%>
        </ul>
      </div>

    </div>

  </div>

  <div class="content_float_right">
    <% if @notices.size > 0 then%>
      <div class='title'>
          最新公告
      </div>

      <ul>
        <% if @notices != nil%>
          <% @notices.each do |n|%>
            <li>
              <% if n!=nil then%>
                <%= link_to((truncate n.title,:length=>18),n,:style=>"text-decoration:none;color:#333")%> <span class="date"><%= n.created_at.strftime("%Y-%m-%d")%></span>
              <% end%>
            </li>
          <% end%>
        <% end%>
      </ul>
    <% end%>
  </div>

  <div class="clear">
  </div>
</div>

app/views/page/_footer.html.erb
<div style="clear:both;">&nbsp;</div> 
<div class="Book_Line_01"> 
</div> 
<table style="margin:0 auto;" border="0" cellpadding="0" cellspacing="0" width="950"> 
  <tbody><tr> 
      <td valign="top"> 
        <style type="text/css"> 
          <!--
          .STYLE1 {color: #9B0000;font-size:12px;}
          -->
        </style> 

      </td> 
    </tr> 
    <tr> 
      <td valign="top"> 
        <p align="center">&nbsp;俞氏文化 版权所有&nbsp;&nbsp; Copyright &#169; 2004 - 2012&nbsp;&nbsp; <a href="http://www.miibeian.gov.cn/">京 ICP 备 05051705 号</a> <br><a href="<%= root_path%>">www.readinglife.com</a>&nbsp; All Rights Reserved&nbsp;&nbsp;&nbsp;&nbsp;
        <script language="JavaScript" src="./新经典悦读网-新经典文化_files/stat.php"></script><a href="http://www.cnzz.com/stat/website.php?web_id=1994629" target="_blank" title="站长统计"><%= image_tag "pic.gif" ,:border=>"0", :hspace=>"0", :vspace=>"0"%></a><%= image_tag "stat.htm", :border=>"0", :width=>"0",:height=>"0"%> 
        </p> 
        <p align="center">地址：长沙市湖南人民出版社&nbsp; 总机：010-68423599&nbsp; </p> 
      </td> 
    </tr> 
</tbody></table> 

app/views/page/_home_left_column.html.erb
<div class="float_left" style="width: 685px; text-align: center;"> 

  <div class="Book_Left_Title0"> 
    <h1>
      经典书情·书评</h1> 
  </div> 

  <%= render :partial => 'newstar_box' %>
  <div class="DivBlank"></div> 
  <%= render :partial => 'author_flow' %>
  <div class="Book_Line_01"> 
  </div> 
  <div class="DivBlank" style="height:4px;"> 
  </div> 
</div> 

app/views/page/_newstar_box.html.erb
<div class="index02_body">
  <div class="type_list">
    <ul>
      <% Category.all.each do |c|%>
        <li onmouseover="javascript:showtype(<%= c.id%>,<%= Category.all.length%>);"><%= link_to c.name,category_path(c),:id=>"type_0"+c.id.to_s,:class =>if c.id ==1 then "type_list_selected" end %></li>
      <% end%>
    </ul>
  </div>

  <% Category.all.each do |c|%>
    <ul class="goods_list" id="type_list_0<%= c.id%>" style=<%= unless c.id ==1  then "display:none;" end%>>
      <% c.get_products_for_nsbox(9).each do |product|%>
        <% if product != nil%>
        <li>
        <div><a href="<%= product_path(product)%>" target="_blank"><%= image_tag product.image.url%></a></div>
        <dl>
          <dt><%= link_to product.title,product_path(product)%></dt>
          <dd>
          <% if product.author != nil%>
            <strong><%= link_to product.author.name,author_path(product.author)%></strong>
          <% end%>  
          <%= product.description%></dd>
        </dl>
        </li>
        <% end%>
      <% end%>  
    </ul>
  <% end%>

</div>

app/views/page/admin.html.erb
<h2>管理页面</h2>
<div class='row-fluid'>
  <div class='span2'>
  </div>
  <div class='span8'>
    <table class="table">
      <tbody>
        <tr>
          <td>书目</td>
          <td><%= link_to "新增",new_product_path, :class=>'btn'%></td>
          <td><%= link_to "查看所有",products_path, :class => 'btn'%></td>
        </tr>

        <tr>
          <td>头图(743*235)</td>
          <td><%= link_to "新增",new_book_flow_path,:class=>'btn'%></td>
          <td><%= link_to "查看所有",book_flows_path, :class=>'btn'%></td>
        </tr>

        <tr>
          <td>分类页面</td>
          <td></td>
          <td><%= link_to "查看所有", categories_path, :class=>'btn'%></td>
        </tr>

        <tr>
          <td>特色服务</td>
          <td></td>
          <td><%= link_to "查看所有",brands_path, :class=>'btn'%></td>
        </tr>

        <tr>
          <td>作者风采</td>
          <td><%= link_to "新增",new_e_reading_path,:class=>'btn'%></td>
          <td><%= link_to "查看所有",e_readings_path, :class=>'btn'%></td>
        </tr>

        <tr>
          <td>活动现场</td>
          <td><%= link_to "新增", new_news_path,:class=>'btn'%></td>
          <td><%= link_to "查看所有",news_admin_path, :class=>'btn'%></td>
        </tr>
        <tr>
          <td>出版须知</td>
          <td><%= link_to "新增", new_event_path,:class=>'btn'%></td>
          <td><%= link_to "查看所有",events_admin_path, :class=>'btn'%></td>
        </tr>
        <tr>
          <td>最新公告</td>
          <td><%= link_to "新增", new_notice_path,:class=>'btn'%></td>
          <td><%= link_to "查看所有",notices_admin_path, :class=>'btn'%></td>
        </tr>
        <tr>
          <td>关注榜</td>
          <td></td>
          <td><%= link_to "编辑",best_sellers_path, :class=>'btn'%></td>
        </tr>
        <tr>
          <td>下载管理</td>
          <td><%= link_to "新增", new_doc_path,:class=>'btn'%></td>
          <td><%= link_to "查看所有",docs_admin_path, :class=>'btn'%></td>
        </tr>

      </tbody>
    </table>
  </div>
</div>