config/routes.rb
BookStore::Application.routes.draw do

  get "notices/admin"
  resources :notices

  get "docs/admin"

  resources :docs

  get "events/admin"
  resources :events

  resources :brands

  resources :e_readings

  get "book_flow/new"

  get "book_flow/create"

  get "book_flow/edit"

  get "book_flow/update"

  get "book_flow/destroy"

  get "book_flow/show"

  get "book_flow/index"

  get "sessions/new"

  resources :sessions,:only=>[:new,:create,:destroy]

  match '/signup',:to=>'users#new'
  match '/signin',:to => 'sessions#new'
  match '/signout',:to=> 'sessions#destroy'
  match '/search',:to=>'products#search'
  match '/admin', :to => 'page#admin'

  resources :book_flows do

  end

  resources :users

  resources :best_sellers

  get "news/admin"
  resources :news

  resources :publishers

  resources :authors

  resources :categories

  get "products/book_list"

  resources :products

  get "books/index"

  get "books/show"

  get "books/destroy"

  get "books/create"

  get "books/new"

  get "book/index"

  get "book/new"

  get "book/destroy"

  root :to=> "page#home"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :image, :name, :story
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename"

  has_many :products,:dependent => :destroy

  def get_products_for_nsbox(num=9)
    result = Product.where("category_id = ?",self.id)[0...num]
    #if result is shorter than required,fill up with nil
    if result.length < num
      result+[nil]*(num - result.length)
    else
      result
    end
  end
end

# == Schema Information
#
# Table name: categories
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

# == Schema Information
#
# Table name: categories
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate,:only=>[:index,:edit,:new,:create,:destroy,:update]

  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    render :layout => "admin"

    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.xml  { render :xml => @categories }
    #end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])
    # @products = @category.products
    @story = @category.story
    @best_sellers = BestSeller.get(7)
    @title = @category.name
    @withReview = Product.pickOneWithReview

    @notices = Notice.get_notices(6)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :story %><br />
    <%= f.text_area :story %>
  </div>
  <div class="field">
    <%= f.label "上传图片"%><br />
    <%= f.file_field :image%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_story.html.erb
<div class="sales_left">
  <div class="content_float_left_top">
    <div style="float: left; text-align:left;color:#cb651b;font-size: 14px;font-weight:bold;padding-top: 11px;padding-left: 20px">
      <%= @title||'热销'%>
    </div>
    <div style="float: right;font-size: 13px;color:white;padding-right: 20px;padding-top: 10px">
    </div>
  </div>

  <div class="content_float_left_middle">
  </div>

  <div class="content_float_left_bottom">
    <%= image_tag(@category.image(:medium), :class => :category_img, :alt => "类别图片") if @category.image.present? %>
    <p ><%= simple_format @story%></p>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table class='table'>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category, :class => 'btn' %></td>
    <td><%= link_to 'Edit', edit_category_path(category), :class => 'btn' %></td>
    <!-- <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td> -->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="content" style="position: relative;top:-15px;">

  <div class="content_sales">
    <%= render :partial => 'categories/story' %>
    <%= render :partial => 'products/sales_right'%>
  </div>

  <%= render :partial => 'page/content_bottom' %>

  <div class="clear"></div>

</div>