config/routes.rb
BookStore::Application.routes.draw do

  get "notices/admin"
  resources :notices

  get "docs/admin"

  resources :docs

  get "events/admin"
  resources :events

  resources :brands

  resources :e_readings

  get "book_flow/new"

  get "book_flow/create"

  get "book_flow/edit"

  get "book_flow/update"

  get "book_flow/destroy"

  get "book_flow/show"

  get "book_flow/index"

  get "sessions/new"

  resources :sessions,:only=>[:new,:create,:destroy]

  match '/signup',:to=>'users#new'
  match '/signin',:to => 'sessions#new'
  match '/signout',:to=> 'sessions#destroy'
  match '/search',:to=>'products#search'
  match '/admin', :to => 'page#admin'

  resources :book_flows do

  end

  resources :users

  resources :best_sellers

  get "news/admin"
  resources :news

  resources :publishers

  resources :authors

  resources :categories

  get "products/book_list"

  resources :products

  get "books/index"

  get "books/show"

  get "books/destroy"

  get "books/create"

  get "books/new"

  get "book/index"

  get "book/new"

  get "book/destroy"

  root :to=> "page#home"

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :author
  belongs_to :publisher
  belongs_to :category
  belongs_to :brand

  validates :price,:numericality=>{:greater_than_or_equal_to => 0.1}

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
         :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
         :url => "/system/:attachment/:id/:style/:filename"

  def self.with_review(count)
    Product.order("created_at ASC").where("review IS NOT NULL")[0...count]
  end

  def self.pickOneWithReview
    #TODO TMP IMPL,add random
    with_review(1)[0]
  end

  def self.get(count)
    Product.order("created_at ASC")[0...count]
  end
end













# == Schema Information
#
# Table name: products
#
#  id                 :integer         not null, primary key
#  title              :string(255)
#  description        :string(255)
#  price              :decimal(, )
#  created_at         :datetime
#  updated_at         :datetime
#  promote_img_name   :string(255)
#  is_for_youth       :boolean         default(FALSE)
#  category_id        :integer
#  author_id          :integer
#  publisher_id       :integer
#  review             :text
#  dangdang_link      :string(255)
#  format             :string(255)
#  pubdate            :string(255)
#  page               :integer
#  brand_id           :integer
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate,:only=>[:new,:create,:edit,:destroy,:update,:index]

  # GET /products
  # GET /products.xml
  def index
    @products = Product.order("updated_at DESC").all

    render :layout => "admin"
    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.xml  { render :xml => @products }
    #end
  end

  def book_list
    list_name = params[:list_name]
    @product_list = Product.where({"#{list_name}" => true}).order("updated_at DESC")

  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])
    @best_sellers = BestSeller.get(7)
    @withReview = Product.pickOneWithReview()
    @notices = Notice.get_notices(6)

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    @categories = Category.all

    render :layout => 'admin'
    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.xml  { render :xml => @product }
    #end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])

    render :layout => "admin"
  end

  # POST /products
  # POST /products.xml
  def create
    params.delete("author_id") if params[:author_id] == -1
    params.delete("brand_id") if params[:brand_id] == -1

    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    #uploaded_io = params[:picture]

    #if uploaded_io != nil
    #  File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'w') do |file|
    #    file.write(uploaded_io.read)

    #    params[:product][:image_url] = "/uploads/"+ uploaded_io.original_filename
    #  end
    #end
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end

  def search
    @best_sellers = BestSeller.get(7)
    @title = "Search for " + params[:q]
    @withReview = Product.pickOneWithReview()

    @products = Product.where("title LIKE ?","%#{params[:q]}%")
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_douban_book_list.html.erb
<% if @products != nil%>
  <% @products.each do |product|%>
    <p id="<%= product.id%>" class="ul"></p>
    <table width="100%">
      <tbody>
        <tr class="doulist_item">
          <td width="100" valign="top">
            <a href="<%= product_path(product)%>"><%= image_tag product.image_url,:style => "max-width:145px;max-height:200px;margin:10px"%></a>
          </td>
          <td valign="top">
            <div class="pl2" style = "margin-top:10px;margin-left:6px">
              <span class="rr pl"><%= product.created_at.strftime("%Y-%m-%d ")%>添加</span>
              <%= link_to product.title,product_path(product)%>
            </div>
            <p class="pl" style = "margin:5px">
              作者 : 
                <%=if product.author != nil then link_to product.author.name,author_path(product.author) end%>
              <br/>
              </p>
             <p class="pl" style = "margin:5px"> 出版社 : 
             <%= if !product.publisher.nil? then product.publisher.name end%>
            </p>
            <p>
              <span class="pl" style = "margin:5px">
                评语
              </span> : 
                <%= product.description%>
            </p> 
            <div class="clearfix"></div>
          </td>
        </tr>
      </tbody>
    </table>
  <% end%>
<% end%>

app/views/products/_form.html.erb
<%= javascript_include_tag "author_list" %>

<div class='row-fluid'>
  <div class='span3'>
  </div>
  <div class='span5'>
    <%= form_for(@product,:html => {:multipart => true, :class => 'form-horizontal'}) do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% @product.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class='fieldset'>
        <div class="control-group">
          <%= f.label "书名:", :class => 'control-label' %>
          <div class='controls'>
            <%= f.text_field :title %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "简介:", :class => 'control-label'%>
          <div class='controls'>
            <%= f.text_area :description %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "书评:", :class => 'control-label'%>
          <div class='controls'>
            <%= f.text_area :review%>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "价格:", :class => 'control-label' %>
          <div class='controls'>
            <%= f.text_field :price %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "当当链接:", :class => 'control-label' %>
          <div class='controls'>
            <%= f.text_field :dangdang_link %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "开本:", :class => 'control-label' %>
          <div class='controls'>
            <%= f.text_field :format %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "出版日期:",:class => 'control-label' %>
          <div class='controls'>
            <%= f.text_field :pubdate %>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "页数:", :class => 'control-label' %>
          <div class='controls'>
            <%= f.text_field :page %>
          </div>
        </div> 

        <div class="control-group">
          <%= f.label "作者:",:class => 'control-label'%>
          <div class='controls'>
            <%= f.select(:author_id, Author.all.map{|a| [a.name,a.id]}.insert(0,["无",-1]) )%>
            <p><%= link_to "创建作者",new_author_path, :target => '_blank'%></p>
          </div>
        </div>

        <!--
        <div class="control-group">
          <%= f.label "类别:", :class => 'control-label'%>
          <div class='controls'>
            <%= f.select(:category_id,Category.all.map{|c| [c.name,c.id]})%>
          </div>
        </div>

        <div class="control-group">
          <%= f.label "品牌:", :class => 'control-label'%>
          <div class='controls'>
            <%= f.select(:brand_id,Brand.all.map{|b| [b.name,b.id]}.insert(0,["无",-1]) )%>
          </div>
        </div>
        -->

        <div class="control-group">
          <%= label_tag "上传图片:",nil, :class => 'control-label' %>
          <div class='controls'>
            <%= f.file_field 'image'%>
          </div>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/_hunan_book_list.html.erb
<div class="sales_left">
  <div class="content_float_left_top">
    <div style="float: left; text-align:left;color:#cb651b;font-size: 14px;font-weight:bold;padding-top: 11px;padding-left: 20px">
      <%= @title||'热销'%>
    </div>
    <div style="float: right;font-size: 13px;color:white;padding-right: 20px;padding-top: 10px">
    </div>
  </div>

  <div class="content_float_left_middle">
  </div>

  <div class="content_float_left_bottom">
    <ul>
      <% @products.each do |product|%>
        <li>
        <div class="book_img">
          <%= link_to (image_tag product.image.url(:medium),:style => "max-width:118px;max-height:190px;height:auto !important;"),product%>      </div>
        <div class="disc">
          <div class="title"><%= link_to product.title,product,:class=>'orange'%></div>
          <div class="brf">
            <%= simple_format truncate(product.description,:length=>200)%>
          </div>
          <div class="writer">
            <%if product.author != nil%>
              作者：
              <%=link_to product.author.name,author_path(product.author),:class=>'gray' %>
            <% end%>
          </div>
          <div class="price">
            ￥<%= product.price%>
          </div>

        </div>
        <div class="clear">

        </div>
        <hr>

        </li>
      <% end%>
    </ul>
  </div>

</div>

app/views/products/_right_column.html.erb
<div style="width: 200px; float: right; text-align: center;">


  <div class="myborder">
    <div class="Book_Left_Title0" style="cursor: pointer; width: 90%; padding-left: 3px; margin: 0 auto;">
      <a href="/Book/Award.aspx">
        <h1>
          大奖图书</h1>
      </a>
    </div>
    <div class="DivBlank">
    </div>
    <div style="width: 88%; margin: 0 auto; text-align: left; overflow:hidden;">
      <div id="ctl00_CenterContent_ChinaL_Ad_Commend_01" style="width: 98%; text-align: left; margin: 0 auto; overflow: hidden; line-height:200%;"><STRONG><FONT style="COLOR: #3f3b3a; FONT-SIZE: 14px">图书</FONT> <BR></STRONG>茅盾文学奖：<A href="/Goods/Book-110009120289.html">平凡的世界</A> <BR>茅盾文学奖：<A href="/Goods/Book-110009120292.html">白鹿原</A> <BR>茅盾文学奖：<A href="/Goods/Book-110009120288.html">穆斯林的葬礼</A> <BR>华语文学传媒大奖：<A href="/Goods/Book-110009120053.html">金山</A><BR>中山杯华侨文学奖评委会特别奖：<A href="/Goods/Book-110009120053.html">金山</A> <BR>北京文化艺术奖：<A href="/Goods/Book-110009120313.html">红煤</A> <BR>老舍文学奖：<A href="/Goods/Book-110009120054.html">受活</A> <BR><BR><STRONG><FONT style="COLOR: #3f3b3a; FONT-SIZE: 14px">作家</FONT> <BR></STRONG>茅盾文学奖：<A href="/luyao">路遥</A> <BR>茅盾文学奖：<A href="/chenzhongshi">陈忠实</A> <BR>茅盾文学奖：<A href="/huoda">霍达</A> <BR>茅盾文学奖：<A href="zhoudaxin">周大新</A> <BR>鲁迅文学奖：<A href="/liuqingbang">刘庆邦</A> <BR>老舍文学奖：<A href="/liuqingbang">刘庆邦</A> <BR>庄重文文学奖：<A href="/lier">李洱</A> <BR>庄重文文学奖：<A href="/gaojianqun">高建群</A></div>

    </div>
    <div class="DivBlank">
    </div>
    <div class="DivBlank">
    </div>
  </div>
  <div class="DivBlank">
  </div>
  <div class="myborder" style="text-align: center;">
    <div class="Book_Left_Title0" style="width: 90%; padding-left: 3px; margin: 0 auto;">
      <h1 id="ctl00_CenterContent_LSortName0">华语文学导航</h1>
    </div>
    <div class="DivBlank">
    </div>
    <div style="width: 88%; margin: 0 auto; text-align: left;">
      <table id="ctl00_CenterContent_Table1" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td align="left">
            <h3 id="ctl00_CenterContent_LSortName1">
              书系</h3>
          </td>
        </tr>
        <tr>
          <td style="text-align: left;" valign="top">
            <div id="ctl00_CenterContent_Detail_shuxi_ad" style="margin: 0 auto;"><A href="/Book/ListBook.aspx?QSortId=60093">张爱玲作品</A> <BR><A href="/Book/ListBook.aspx?QSortId=60107">三毛作品</A> <BR><A href="/Book/ListBook.aspx?QSortId=60108">张小娴作品 <BR><A href="/Book/ListBook.aspx?QSortId=60109">安妮宝贝作品 <BR><A href="/Book/ListBook.aspx?QSortId=60126">路遥作品 <BR><A href="/Book/ListBook.aspx?QSortId=60110">沈从文集 <BR><A href="/Book/ListBook.aspx?QSortId=60125">陈忠实集 <BR><A href="/Book/ListBook.aspx?QSortId=60128">老舍作品 <BR><A href="/Book/ListBook.aspx?QSortId=60127">高建群作品 <BR><A href="/Book/ListBook.aspx?QSortId=60138">侯文咏作品 <BR><A href="/Book/ListBook.aspx?QSortId=60133">阎连科作品</A></div>
                          </td>
                        </tr>
                      </table>

                      <table id="ctl00_CenterContent_DivZhuanti" cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                          <td align="left">
                            <div class="DivBlank">
                            </div>
                            <h3 id="ctl00_CenterContent_LSortName2">
                              专题</h3>
                          </td>
                        </tr>
                        <tr>
                          <td style="" valign="top">


                            <div>
                              <a
                                href='/GSpecial/Special-751110260001.html'
                                target="_blank" title='安妮宝贝十年典藏文集'>安妮宝贝十年典藏文集</a>
                            </div>

                            <div>
                              <a
                                href='/GSpecial/Special-751003100001.html'
                                target="_blank" title='海鸥乔纳森：敢想敢做敢与众不同'>海鸥乔纳森：敢想敢做敢与众不同</a>
                            </div>

                            <div>
                              <a
                                href='/GSpecial/Special-751001020009.html'
                                target="_blank" title='安妮宝贝-清醒纪'>安妮宝贝-清醒纪</a>
                            </div>

                            <div>
                              <a
                                href='/GSpecial/Special-751001020008.html'
                                target="_blank" title='我，终究是爱你的'>我，终究是爱你的</a>
                            </div>

                            <div>
                              <a
                                href='/GSpecial/Special-751001020002.html'
                                target="_blank" title='我们一起怀念路遥'>我们一起怀念路遥</a>
                            </div>

                          </td>
                        </tr>
                      </table>

                    </div>
                    <div class="DivBlank">
                    </div>
                  </div>
                  <div class="DivBlank">
                  </div>
                  <div style="display: none;">
                    <div class="Book_Left_Title0" style="width:90%; padding-left: 3px; margin: 0 auto;">
                      新经典简报
                    </div>
                    <div style="width: 96%; margin: 0 auto;">

                    </div>
                    <div class="DivBlank">
                    </div>
                  </div>
                  <div style="display: none;">
                    <div style="width: 100%; text-align: left;">
                      <span class="Book_Left_Title">&nbsp;<span id="ctl00_CenterContent_ClientClubTitle">新经典悦读俱乐部开张啦！</span></span>
                    </div>
                    <div style="width: 98%; text-align: left; text-indent: 2pc; margin: 0 auto; height: auto !important; height: 220px; min-height: 220px;">
                      经典悦读俱乐部依托新经典文化有限公司和旗下网站新经典悦读网成立。 读书也许不一定能改变命运，但一定能改变我们的内心世界，让我们变得更美好、向善、有力量…… 读经典的书，做有心的人，这是我们的宗旨。如果您也这么认为，如果您也喜欢那些被时光印证过的永远的经典，那么，现在就——
                      <br />
                      <div style="text-align: right; width: 100%;">
                        <a href="/Client/ClientReg.aspx">申请加入经典悦读俱乐部 >> </a>
                      </div>
                    </div>
                  </div>
                  <div class="DivBlank">
                  </div>
                  <div id="ctl00_CenterContent_Detail_other_ad" style="margin: 0 auto; width: 98%; overflow: hidden;"><P>&nbsp;</P>
                    <P>&nbsp;</P></div>

                </div>

app/views/products/_sales_right.html.erb
<div class="sales_right">
  <div class="content_float_right_1">


    <% if @notices.size > 0 then%>
      <div class='title'>
          最新公告
      </div>

      <ul>
        <% if @notices != nil%>
          <% @notices.each do |n|%>
            <li>
              <% if n!=nil then%>
                <%= link_to((truncate n.title,:length=>18),n,:style=>"text-decoration:none;color:#333")%> <span class="date"><%= n.created_at.strftime("%Y-%m-%d")%></span>
              <% end%>
            </li>
          <% end%>
        <% end%>
      </ul>
    <% end%>


  </div>
  <div class="content_float_right_2">
    <div class="content_float_right_top" style="background-image: url('/images/left_top.png');height: 38px;">
      <div class="text_top">畅销榜</div>
    </div>
    <div class="content_float_right_middle">
      <% i = 0%>
      <% @best_sellers.each do |book|%>
        <% if book != nil%>
          <% i+=1%>
          <div class="right_cont">
            <div class="left">
              <%= link_to((image_tag book.image.url(:thumb),:size=>"61x89"),book) %>
            </div>
            <div class="right">
              <h1>
                0<%= i%>
              </h1>
              <p>
              <%= link_to((truncate book.title,:length=>9),book,:class=>'gray') %>
              </p>
              <span class="writer">
                <%= if book.author!=nil then "作者：" + truncate(book.author.name,:length=>9) end%>
              </span>
            </div>
            <div class="clear"></div>
          </div>
          <div class="divi"></div>
        <% end%>
      <% end%>  
    </div>

    <div class="content_float_right_bottom" style="position:relative;top:-10px;background-image: url('/images/left_bottom.png');height: 7px">
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>管理书籍</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>所有图书</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>书籍编号</th>
      <th>书名</th>
      <th>简介</th>
      <th>价格</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="span2"><%= image_tag product.image.url(:medium),:size=>'80x120' %></td>
        <td ><%= product.id %></td>
        <td class="span3"><%= link_to product.title,product%></td>
        <td class="span4"><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to '编辑', edit_product_path(product) %></td>
        <td><%= link_to '删除', product, :confirm => '确定删除?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to '新建书籍', new_product_path %>

app/views/products/new.html.erb
<h2>新建图书</h2>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<div class="content" style="position: relative;top:-15px;">

  <div class="content_sales">
    <%= render :partial => 'products/hunan_book_list' %>
    <%= render :partial => 'products/sales_right'%>
  </div>

  <%= render :partial => 'page/content_bottom' %>

  <div class="clear"></div>

</div>

app/views/products/show.html.erb
<div class="content" style="position: relative;top:-15px;">

  <div class="content_sales">
    <div class="sales_left">
      <div class="content_float_left_top" style="height: 15px;">
      </div>

      <div class="content_float_left_middle">
      </div>

      <div class="content_book_detail">
        <div class="top">
          <div class="book_img">
            <%= image_tag @product.image.url(:medium)%>
            <% if !@product.dangdang_link.blank?%>
              <%= link_to image_tag("buy.png", :alt => "buy", :width => 113, :height => 42, :title => "Click here to dangdang"), @product.dangdang_link %>
            <% end%>
          </div>
          <div class="disc"  style="text-align: left;">
            <div class="title">
              <%= @product.title%>
            </div>

            <div class="writer" >
              <% if !@product.author.blank? %>
                作　　者：<%= link_to @product.author.name,author_path(@product.author),:class=>:gray %>
              <% end%>
            </div>
            <div class="writer" >
              <% if !@product.format.blank? %>
                开　　本：<%= @product.format %>
              <% end%>
            </div>
            <div class="writer" >
              <% if !@product.page.blank? %>
                页　　数：<%= @product.page %>
              <% end%>
            </div>
            <div class="writer" >
              <% if !@product.pubdate.blank? %>
                出版日期：<%= @product.pubdate %>
              <% end%>
            </div>

            <div class="price" >
              <% if !@product.price.blank? %>
                ￥<%= @product.price%>
              <% end%>
            </div>
          </div>
          <div class="clear"></div>
        </div>

        <hr style="width: 600px;margin-left: 0px;" >

        <div class="bottom">
          <h2 align="left" style="font-weight: normal;font-size: 15px;">内容简介</h2>
          <p ><%= simple_format @product.description%></p>

          <% if !@product.review.blank? %>
            <h2 align="left" style="font-weight: normal;font-size: 15px;margin-top: 55px;">书评</h2>
            <p ><%= simple_format @product.review%></p>
          <% end%>
        </div>
      </div>
    </div>

    <%= render :partial => 'sales_right'%>
  </div>

  <%= render :partial => 'page/content_bottom' %>
  <div class="clear"></div>

</div>